### ISSUE TITLE
Windowed counter doesn't move buckets when expected

### ISSUE THREAD

**Issue by jhalterman** [bradenaw/backpressure#1]
I noticed that the windowed counter implementation doesn't move buckets when expected since it computes `elapsed` time from the `last` time the window was accessed, rather than the start time of the current bucket. Here's a failing test:

```go
func TestWindowdedCounter(t *testing.T) {
	now := time.Time{}
	counter := newWindowedCounter(now, time.Second, 4)

	now = now.Add(900 * time.Millisecond)
	counter.add(now, 1)
	assert.Equal(t, 1, counter.get(now))

	now = now.Add(900 * time.Millisecond)
	counter.add(now, 1) // should be added to bucket 2
	assert.Equal(t, 1, counter.get(now)) // fails
}
```

**Comment by bradenaw** [comment]
Nice find, thank you!

https://github.com/bradenaw/backpressure/commit/1f259836968124fec80e6bd0186d3135274df0ad
